# Generated by Django 4.2.3 on 2023-10-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customeuser_is_verified_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
