# Generated by Django 4.2.3 on 2023-07-24 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_content_alter_course_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='statuse',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 1, 20, 51, 704468)),
        ),
    ]
