# Generated by Django 4.2.3 on 2023-09-01 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_schedule_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 1, 16, 52, 3, 632459)),
        ),
    ]
