# Generated by Django 4.2.3 on 2023-07-25 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_image_alter_course_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 10, 47, 7, 297443)),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ImageField(default='teacher.PNG', upload_to='trainer'),
        ),
    ]
